### ISSUE TITLE
Source code of check.exe?

### ISSUE THREAD

**Issue by QianXiquq** [CusetVoidAldehyde/DataGenerator#1]
传 .exe 不传源文件，你传牛魔 Github 呢。
Manual downvote.

**Comment by TZYLT** [comment]
Manual downvote +1.

**Comment by CusetVoidAldehyde** [comment]
@QianXiquq 我草似你的🐎

**Comment by QianXiquq** [comment]
@CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde @CusetVoidAldehyde Byd.

**Comment by CusetVoidAldehyde** [comment]
@QianXiquq 啥比。

**Comment by CusetVoidAldehyde** [comment]
# @QianXiquq 操你妈
